<?php
/**
 * EvalResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flagr\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".
 *
 * OpenAPI spec version: 1.1.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Flagr\Client\Model;

use \ArrayAccess;
use \Flagr\Client\ObjectSerializer;

/**
 * EvalResult Class Doc Comment
 *
 * @category Class
 * @package  Flagr\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EvalResult implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'evalResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'eval_context' => '\Flagr\Client\Model\EvalContext',
'eval_debug_log' => '\Flagr\Client\Model\EvalDebugLog',
'flag_id' => 'int',
'flag_key' => 'string',
'flag_snapshot_id' => 'int',
'segment_id' => 'int',
'timestamp' => 'string',
'variant_attachment' => 'object',
'variant_id' => 'int',
'variant_key' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'eval_context' => null,
'eval_debug_log' => null,
'flag_id' => 'int64',
'flag_key' => null,
'flag_snapshot_id' => 'int64',
'segment_id' => 'int64',
'timestamp' => null,
'variant_attachment' => null,
'variant_id' => 'int64',
'variant_key' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'eval_context' => 'evalContext',
'eval_debug_log' => 'evalDebugLog',
'flag_id' => 'flagID',
'flag_key' => 'flagKey',
'flag_snapshot_id' => 'flagSnapshotID',
'segment_id' => 'segmentID',
'timestamp' => 'timestamp',
'variant_attachment' => 'variantAttachment',
'variant_id' => 'variantID',
'variant_key' => 'variantKey'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'eval_context' => 'setEvalContext',
'eval_debug_log' => 'setEvalDebugLog',
'flag_id' => 'setFlagId',
'flag_key' => 'setFlagKey',
'flag_snapshot_id' => 'setFlagSnapshotId',
'segment_id' => 'setSegmentId',
'timestamp' => 'setTimestamp',
'variant_attachment' => 'setVariantAttachment',
'variant_id' => 'setVariantId',
'variant_key' => 'setVariantKey'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'eval_context' => 'getEvalContext',
'eval_debug_log' => 'getEvalDebugLog',
'flag_id' => 'getFlagId',
'flag_key' => 'getFlagKey',
'flag_snapshot_id' => 'getFlagSnapshotId',
'segment_id' => 'getSegmentId',
'timestamp' => 'getTimestamp',
'variant_attachment' => 'getVariantAttachment',
'variant_id' => 'getVariantId',
'variant_key' => 'getVariantKey'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['eval_context'] = isset($data['eval_context']) ? $data['eval_context'] : null;
        $this->container['eval_debug_log'] = isset($data['eval_debug_log']) ? $data['eval_debug_log'] : null;
        $this->container['flag_id'] = isset($data['flag_id']) ? $data['flag_id'] : null;
        $this->container['flag_key'] = isset($data['flag_key']) ? $data['flag_key'] : null;
        $this->container['flag_snapshot_id'] = isset($data['flag_snapshot_id']) ? $data['flag_snapshot_id'] : null;
        $this->container['segment_id'] = isset($data['segment_id']) ? $data['segment_id'] : null;
        $this->container['timestamp'] = isset($data['timestamp']) ? $data['timestamp'] : null;
        $this->container['variant_attachment'] = isset($data['variant_attachment']) ? $data['variant_attachment'] : null;
        $this->container['variant_id'] = isset($data['variant_id']) ? $data['variant_id'] : null;
        $this->container['variant_key'] = isset($data['variant_key']) ? $data['variant_key'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets eval_context
     *
     * @return \Flagr\Client\Model\EvalContext
     */
    public function getEvalContext()
    {
        return $this->container['eval_context'];
    }

    /**
     * Sets eval_context
     *
     * @param \Flagr\Client\Model\EvalContext $eval_context eval_context
     *
     * @return $this
     */
    public function setEvalContext($eval_context)
    {
        $this->container['eval_context'] = $eval_context;

        return $this;
    }

    /**
     * Gets eval_debug_log
     *
     * @return \Flagr\Client\Model\EvalDebugLog
     */
    public function getEvalDebugLog()
    {
        return $this->container['eval_debug_log'];
    }

    /**
     * Sets eval_debug_log
     *
     * @param \Flagr\Client\Model\EvalDebugLog $eval_debug_log eval_debug_log
     *
     * @return $this
     */
    public function setEvalDebugLog($eval_debug_log)
    {
        $this->container['eval_debug_log'] = $eval_debug_log;

        return $this;
    }

    /**
     * Gets flag_id
     *
     * @return int
     */
    public function getFlagId()
    {
        return $this->container['flag_id'];
    }

    /**
     * Sets flag_id
     *
     * @param int $flag_id flag_id
     *
     * @return $this
     */
    public function setFlagId($flag_id)
    {
        $this->container['flag_id'] = $flag_id;

        return $this;
    }

    /**
     * Gets flag_key
     *
     * @return string
     */
    public function getFlagKey()
    {
        return $this->container['flag_key'];
    }

    /**
     * Sets flag_key
     *
     * @param string $flag_key flag_key
     *
     * @return $this
     */
    public function setFlagKey($flag_key)
    {
        $this->container['flag_key'] = $flag_key;

        return $this;
    }

    /**
     * Gets flag_snapshot_id
     *
     * @return int
     */
    public function getFlagSnapshotId()
    {
        return $this->container['flag_snapshot_id'];
    }

    /**
     * Sets flag_snapshot_id
     *
     * @param int $flag_snapshot_id flag_snapshot_id
     *
     * @return $this
     */
    public function setFlagSnapshotId($flag_snapshot_id)
    {
        $this->container['flag_snapshot_id'] = $flag_snapshot_id;

        return $this;
    }

    /**
     * Gets segment_id
     *
     * @return int
     */
    public function getSegmentId()
    {
        return $this->container['segment_id'];
    }

    /**
     * Sets segment_id
     *
     * @param int $segment_id segment_id
     *
     * @return $this
     */
    public function setSegmentId($segment_id)
    {
        $this->container['segment_id'] = $segment_id;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return string
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param string $timestamp timestamp
     *
     * @return $this
     */
    public function setTimestamp($timestamp)
    {
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets variant_attachment
     *
     * @return object
     */
    public function getVariantAttachment()
    {
        return $this->container['variant_attachment'];
    }

    /**
     * Sets variant_attachment
     *
     * @param object $variant_attachment variant_attachment
     *
     * @return $this
     */
    public function setVariantAttachment($variant_attachment)
    {
        $this->container['variant_attachment'] = $variant_attachment;

        return $this;
    }

    /**
     * Gets variant_id
     *
     * @return int
     */
    public function getVariantId()
    {
        return $this->container['variant_id'];
    }

    /**
     * Sets variant_id
     *
     * @param int $variant_id variant_id
     *
     * @return $this
     */
    public function setVariantId($variant_id)
    {
        $this->container['variant_id'] = $variant_id;

        return $this;
    }

    /**
     * Gets variant_key
     *
     * @return string
     */
    public function getVariantKey()
    {
        return $this->container['variant_key'];
    }

    /**
     * Sets variant_key
     *
     * @param string $variant_key variant_key
     *
     * @return $this
     */
    public function setVariantKey($variant_key)
    {
        $this->container['variant_key'] = $variant_key;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
