<?php
/**
 * EvaluationBatchRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flagr\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".
 *
 * OpenAPI spec version: 1.1.12
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Flagr\Client\Model;

use \ArrayAccess;
use \Flagr\Client\ObjectSerializer;

/**
 * EvaluationBatchRequest Class Doc Comment
 *
 * @category Class
 * @package  Flagr\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EvaluationBatchRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'evaluationBatchRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'enable_debug' => 'bool',
'entities' => '\Flagr\Client\Model\EvaluationEntity[]',
'flag_i_ds' => 'int[]',
'flag_keys' => 'string[]',
'flag_tags' => 'string[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'enable_debug' => null,
'entities' => null,
'flag_i_ds' => 'int64',
'flag_keys' => null,
'flag_tags' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'enable_debug' => 'enableDebug',
'entities' => 'entities',
'flag_i_ds' => 'flagIDs',
'flag_keys' => 'flagKeys',
'flag_tags' => 'flagTags'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'enable_debug' => 'setEnableDebug',
'entities' => 'setEntities',
'flag_i_ds' => 'setFlagIDs',
'flag_keys' => 'setFlagKeys',
'flag_tags' => 'setFlagTags'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'enable_debug' => 'getEnableDebug',
'entities' => 'getEntities',
'flag_i_ds' => 'getFlagIDs',
'flag_keys' => 'getFlagKeys',
'flag_tags' => 'getFlagTags'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['enable_debug'] = isset($data['enable_debug']) ? $data['enable_debug'] : null;
        $this->container['entities'] = isset($data['entities']) ? $data['entities'] : null;
        $this->container['flag_i_ds'] = isset($data['flag_i_ds']) ? $data['flag_i_ds'] : null;
        $this->container['flag_keys'] = isset($data['flag_keys']) ? $data['flag_keys'] : null;
        $this->container['flag_tags'] = isset($data['flag_tags']) ? $data['flag_tags'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['entities'] === null) {
            $invalidProperties[] = "'entities' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets enable_debug
     *
     * @return bool
     */
    public function getEnableDebug()
    {
        return $this->container['enable_debug'];
    }

    /**
     * Sets enable_debug
     *
     * @param bool $enable_debug enable_debug
     *
     * @return $this
     */
    public function setEnableDebug($enable_debug)
    {
        $this->container['enable_debug'] = $enable_debug;

        return $this;
    }

    /**
     * Gets entities
     *
     * @return \Flagr\Client\Model\EvaluationEntity[]
     */
    public function getEntities()
    {
        return $this->container['entities'];
    }

    /**
     * Sets entities
     *
     * @param \Flagr\Client\Model\EvaluationEntity[] $entities entities
     *
     * @return $this
     */
    public function setEntities($entities)
    {
        $this->container['entities'] = $entities;

        return $this;
    }

    /**
     * Gets flag_i_ds
     *
     * @return int[]
     */
    public function getFlagIDs()
    {
        return $this->container['flag_i_ds'];
    }

    /**
     * Sets flag_i_ds
     *
     * @param int[] $flag_i_ds flagIDs
     *
     * @return $this
     */
    public function setFlagIDs($flag_i_ds)
    {
        $this->container['flag_i_ds'] = $flag_i_ds;

        return $this;
    }

    /**
     * Gets flag_keys
     *
     * @return string[]
     */
    public function getFlagKeys()
    {
        return $this->container['flag_keys'];
    }

    /**
     * Sets flag_keys
     *
     * @param string[] $flag_keys flagKeys. Either flagIDs, flagKeys or flagTags works. If pass in multiples, Flagr may return duplicate results.
     *
     * @return $this
     */
    public function setFlagKeys($flag_keys)
    {
        $this->container['flag_keys'] = $flag_keys;

        return $this;
    }

    /**
     * Gets flag_tags
     *
     * @return string[]
     */
    public function getFlagTags()
    {
        return $this->container['flag_tags'];
    }

    /**
     * Sets flag_tags
     *
     * @param string[] $flag_tags flagTags. Either flagIDs, flagKeys or flagTags works. If pass in multiples, Flagr may return duplicate results.
     *
     * @return $this
     */
    public function setFlagTags($flag_tags)
    {
        $this->container['flag_tags'] = $flag_tags;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
