<?php
/**
 * EvaluationEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Flagr\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".
 *
 * OpenAPI spec version: 1.1.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Flagr\Client;

/**
 * EvaluationEntityTest Class Doc Comment
 *
 * @category    Class
 * @description EvaluationEntity
 * @package     Flagr\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EvaluationEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EvaluationEntity"
     */
    public function testEvaluationEntity()
    {
    }

    /**
     * Test attribute "entity_context"
     */
    public function testPropertyEntityContext()
    {
    }

    /**
     * Test attribute "entity_id"
     */
    public function testPropertyEntityId()
    {
    }

    /**
     * Test attribute "entity_type"
     */
    public function testPropertyEntityType()
    {
    }
}
