<?php
/**
 * FlagApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".
 *
 * OpenAPI spec version: 1.1.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * FlagApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FlagApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createFlag
     *
     * .
     *
     */
    public function testCreateFlag()
    {
    }

    /**
     * Test case for deleteFlag
     *
     * .
     *
     */
    public function testDeleteFlag()
    {
    }

    /**
     * Test case for findFlags
     *
     * .
     *
     */
    public function testFindFlags()
    {
    }

    /**
     * Test case for getFlag
     *
     * .
     *
     */
    public function testGetFlag()
    {
    }

    /**
     * Test case for getFlagEntityTypes
     *
     * .
     *
     */
    public function testGetFlagEntityTypes()
    {
    }

    /**
     * Test case for getFlagSnapshots
     *
     * .
     *
     */
    public function testGetFlagSnapshots()
    {
    }

    /**
     * Test case for putFlag
     *
     * .
     *
     */
    public function testPutFlag()
    {
    }

    /**
     * Test case for restoreFlag
     *
     * .
     *
     */
    public function testRestoreFlag()
    {
    }

    /**
     * Test case for setFlagEnabled
     *
     * .
     *
     */
    public function testSetFlagEnabled()
    {
    }
}
