<?php
/**
 * SegmentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Flagr\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".
 *
 * OpenAPI spec version: 1.1.12
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Flagr\Client;

use Flagr\Client\Configuration;
use Flagr\Client\ApiException;
use Flagr\Client\ObjectSerializer;

/**
 * SegmentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Flagr\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SegmentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSegment
     *
     * .
     *
     */
    public function testCreateSegment()
    {
    }

    /**
     * Test case for deleteSegment
     *
     * .
     *
     */
    public function testDeleteSegment()
    {
    }

    /**
     * Test case for findSegments
     *
     * .
     *
     */
    public function testFindSegments()
    {
    }

    /**
     * Test case for putSegment
     *
     * .
     *
     */
    public function testPutSegment()
    {
    }

    /**
     * Test case for putSegmentsReorder
     *
     * .
     *
     */
    public function testPutSegmentsReorder()
    {
    }
}
